### ISSUE TITLE
panic label::span when doing something wrong

### ISSUE THREAD

**Issue by rapenne-s** [tweag/nickel#1021] opened 2022-12-28 15:29 UTC
**Describe the bug**

nickel is crashing instead of handling an error

**To Reproduce**

Create `lib.ncl` with
```
let system-users = Array Num in
import "users.ncl" | system-users
```

Create `users.ncl` with
```
["a"]
```

run
```
> RUST_BACKTRACE=1 nickel -f lib.ncl
thread 'main' panicked at 'label::span: unexpected type system-users with path element Some(Array)', src/label.rs:195:27
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: nickel_lang::label::ty_path::span
   3: nickel_lang::error::blame_error::report_ty_path
   4: <nickel_lang::error::EvalError as nickel_lang::error::ToDiagnostic<codespan::file::FileId>>::to_diagnostic
   5: <nickel_lang::error::Error as nickel_lang::error::ToDiagnostic<codespan::file::FileId>>::to_diagnostic
   6: nickel_lang::program::Program<EC>::report
   7: nickel::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Expected behavior**

nickel should tell me something is wrong

**Environment**
 - NixOS 22.11
 - Nickel 0.3.1

**Comment by matthew-healy** [comment] 2022-12-29 11:26
This can be reproduced without the `import`:

```
let ArrayNum = Array Num in
["a"] | ArrayNum
```

It's worth noting that just `["a"] | Array Num` works fine, so this seems to be a problem with how we resolve contract aliases when assigning blame.

**Comment by matthew-healy** [comment] 2022-12-29 13:38
After a little more investigating: the issue is that the label to which blame is assigned in the generated `%assume%` call has its `types` field set to a `TypeF::Flat` whose `RichTerm` is the `Var` term rather than the bound contract. We panic because we make the (currently incorrect) assumption that flat types can never be indexed by a type path. I think this can be fixed by just resolving the variable in `subcontract` - we seem to already do this for record contract aliases.

**Comment by matthew-healy** [comment] 2022-12-29 16:22
@yannham I've assigned you since you mentioned on Slack you'd already drafted a fix for this.

**Closed** 2023-01-03 14:13 UTC
Labels: type: bug, area: contracts
