### ISSUE TITLE
Exporting as yaml produces ambiguous yaml (base 60 numbers)

### ISSUE THREAD

**Issue by abextm** [tweag/nickel#1368] opened 2023-06-16 05:45 UTC
**Describe the bug**
Exporting documents as yaml produces yaml with unquoted strings, which yaml 1.1 parsers can confuse for other values, such as a base 60 number.

**To Reproduce**
Exporting (`nickel export --format yaml`) `{ port = "22:22" }` produces `port: 22:22`, which when parsed by PyYAML produces the dictionary `{'port': 1342}`

Steps to reproduce the behavior.

**Expected behavior**
nickel exports `port: '22:22'` which is unambiguously parsed by PyYAML

**Environment**
 - Arch Linux
 - `nickel-lang 1.0.0`

**Additional context**
This is not a bug in PyYAML as [yaml 1.1](https://yaml.org/type/int.html) specifies this encoding. This was removed in yaml 1.2, but yaml 1.1 is still common.

**Comment by vkleen** [comment] 2023-06-16 06:16
This is a duplicate of #1222. Thank you for reporting the bug anyway!

**Closed by vkleen** 2023-06-16 06:16 UTC
