### ISSUE TITLE
Issues installing Nickel in a Nix flake devshell

### ISSUE THREAD

**Issue by carletes** [tweag/nickel#1330] opened 2023-05-29 19:15 UTC
I'm trying to set up a development environment for playing around with Nickel using the following Nix flake:

```nix
{
  description = "Nickel experiments";

  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";

    nickel = {
      url = "github:tweag/nickel/1.0-release";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
    };
  };

  outputs = { self, nixpkgs, flake-utils, nickel }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        nickelPkgs = nickel.packages.${system};
      in
      {
        devShells.default = pkgs.mkShell {
          buildInputs = [
            nickelPkgs.nickel

            # Keep this line if you use bash.
            pkgs.bashInteractive
          ];
        };
      });
}
```

The command `nix develop`, however, fails with the following output:

```
carlos@rilke:~/src/nickel-test$ nix develop 2>&1 | tee log
warning: Git tree '/home/carlos/src/nickel-test' is dirty
building '/nix/store/9y1gyjjhfdfca5k3h17lz6xjlp1c1mj1-cargo-1.68.0-x86_64-unknown-linux-gnu.drv'...
building '/nix/store/dqb34wfmnmhvgz79xb33kp0dy429z2p5-rust-src-1.68.0-x86_64-unknown-linux-gnu.drv'...
building '/nix/store/x3zys18x554q3dmps2p50dj3mb1i5slf-rust-std-1.68.0-x86_64-unknown-linux-gnu.drv'...
building '/nix/store/vd1kjxsc3ci88hr248w8i18sq2qb5y1d-rustc-1.68.0-x86_64-unknown-linux-gnu.drv'...
error: builder for '/nix/store/9y1gyjjhfdfca5k3h17lz6xjlp1c1mj1-cargo-1.68.0-x86_64-unknown-linux-gnu.drv' failed with exit code 1;
       last 10 log lines:
       > searching for dependencies of /nix/store/qf2idkhfvsw5jylx6nxs1vc5gkhr7gqs-cargo-1.68.0-x86_64-unknown-linux-gnu/libexec/cargo-credential-1password
       >     libgcc_s.so.1 -> not found!
       > auto-patchelf: 2 dependencies could not be satisfied
       > error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by /nix/store/qf2idkhfvsw5jylx6nxs1vc5gkhr7gqs-cargo-1.68.0-x86_64-unknown-linux-gnu/bin/cargo
       > error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by /nix/store/qf2idkhfvsw5jylx6nxs1vc5gkhr7gqs-cargo-1.68.0-x86_64-unknown-linux-gnu/libexec/cargo-credential-1password
       > auto-patchelf failed to find all the required dependencies.
       > Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
       > /nix/store/mciym69qni8j8rzdndkcqjgh8apk8sxw-stdenv-linux/setup: line 79: pop_var_context: head of shell_variables not a function context
       > /nix/store/mciym69qni8j8rzdndkcqjgh8apk8sxw-stdenv-linux/setup: line 1457: pop_var_context: head of shell_variables not a function context
       > /nix/store/mciym69qni8j8rzdndkcqjgh8apk8sxw-stdenv-linux/setup: line 1594: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/9y1gyjjhfdfca5k3h17lz6xjlp1c1mj1-cargo-1.68.0-x86_64-unknown-linux-gnu.drv'.
error: 1 dependencies of derivation '/nix/store/yvl8ik9009r40dn68bg8lb268fyrd29k-rust-minimal-1.68.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qg7012y6c7byjy0nscqa3q3z6dh7nkqd-nickel-lang-1.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mmz7g4k6ipszsq5sf774yban2h8h3c8j-nix-shell-env.drv' failed to build
carlos@rilke:~/src/nickel-test$ 
```

Any idea what I am doing wrong?

**Comment by vkleen** [comment] 2023-05-30 07:32
Thanks for trying it out! There seem to be some incompatibilities with `rust-overlay` and the newest `nixpkgs`, I guess. There's two ways of fixing this, either you keep the `nixpkgs` version from Nickel pinned:
```
    nickel = {
      url = "github:tweag/nickel/1.0-release";
      # inputs.nixpkgs.follows = "nixpkgs"; <--- just remove this
      inputs.flake-utils.follows = "flake-utils";
    };
```
or you can fetch a new version of the `rust-overlay` like so:
```
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
    };

    nickel = {
      url = "github:tweag/nickel/1.0-release";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
      inputs.rust-overlay.follows = "rust-overlay";
    };
  };

  outputs = { self, nixpkgs, flake-utils, nickel, ... }: # <--- you also need the ... or explicitly rust-overlay as an extra input
```

**Comment by vkleen** [comment] 2023-05-30 10:51
For reference, the issue is https://github.com/oxalica/rust-overlay/issues/121, which has been fixed in `rust-overlay` at https://github.com/oxalica/rust-overlay/commit/c949d341f2b507857d589c48d1bd719896a2a224.

**Closed** 2023-05-30 16:51 UTC
