### ISSUE TITLE
VS Code extension

### ISSUE THREAD

**Issue by ghostsquad** [tweag/nickel#1401] opened 2023-06-23 21:17 UTC
**Is your feature request related to a problem? Please describe.**
It would be very nice (and probably increase adoption) for IDE support, at a minimum, syntax highlighting. I found an unofficial extension (https://github.com/szlend/vscode-nickel), but it is outdated and incompatible with the latest versions of VS Code. Additionally, issues/discussions aren't allowed on the repo to report such problem.

**Describe the solution you'd like**
Create an official VS Code extension to enable syntax highlighting at a minimum.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by yannham** [comment] 2023-06-26 07:56
I think this is a duplicate (or at least a combination) of #1363 and #1364. There is a VS code extension in this repository, but as noted in the aforementioned issues, it doesn't include syntax highlighting and isn't published to the VSCode market place, which should be fixed.

**Comment by simonzkl** [comment] 2023-06-26 08:55
Hm, the unofficial extension works fine for me on the lastest vscode. I think the issue is that it unnecessarily depends on the absolute latest version of vscode engine `"vscode": "^1.79.1"`. Either way, moving the extension in-house would be preferred yeah.

**Comment by szlend** [comment] 2023-06-26 20:52
See https://github.com/tweag/nickel/pull/1405

**Comment by yannham** [comment] 2023-06-30 14:50
The extension has been updated with syntax highlighting (and other fixes) and is now available on the VSCode market place: https://marketplace.visualstudio.com/items?itemName=Tweag.vscode-nickel

**Closed** 2023-06-30 14:50 UTC

**Comment by ghostsquad** [comment] 2023-06-30 20:11
Hooray! 🎉
