### ISSUE TITLE
Test code blocks in documentation

### ISSUE THREAD

**Issue by YorikSar** [tweag/nickel#1294] opened 2023-05-03 18:23 UTC
Documentation contains many code blocks that are not checked by CI and can go stale. I think we could find a way to verify that they work as expected with current version of `nickel` binary.

Quick googling didn't show many tools for this, with [txm](https://github.com/anko/txm) being the most promising. It doesn't seem to support creating some files though.

I found that it would be very easy to miss error in documentation while I was writing [this change](https://github.com/tweag/nickel/commit/87015d7c022662d420dcc3d91e1efc1f1913b124#diff-6a286e849e010b42e1252ea5d2e227a2b846e0f7592540e221e77960d965e2c8) and thought that there should be a better way.

**Comment by vkleen** [comment] 2023-05-03 19:38
This is a duplicate of #1154. It seems we should tackle this sooner rather than later 😅

**Closed by vkleen** 2023-05-03 19:38 UTC
Labels: type: feature request

**Comment by YorikSar** [comment] 2023-05-03 20:10
Huh, I didn't find that one! I guess I was looking for "documentation" and "code block", not "manual" and "code snippet" :D
